apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ibm5v4iq7-go 
  janus-idp.io/tekton: ibm5v4iq7-go
  backstage.io/kubernetes-id: ibm5v4iq7-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ibm5v4iq7-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml